name: Flutter Workflow IOS

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build ios --release --no-codesign
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk,build/app/outputs/ios/release/*.ipa,build/app/outputs/ios/release/*.ipa,build/app/outputs/ios/iphoneos/*.app,build/app/outputs/ios/iphonesimulator/*.app,build/app/ios/*.app,build/app/ios/*.ipa"
          tag: v1.0.${{ github.run_number}}
          token: ${{ secrets.TOKEN }}

      